<?php

/**
 * @file
 * Provides YPKC Salesforce customization.
 */

/**
 * Implements hook_salesforce_branch_memberships_data_alter().
 */
function ypkc_salesforce_traction_rec_branch_memberships_data_alter(array &$data, string $branch_id) {
  // This logic is moved from the plugin to simplify backporting of the plugin.
  $storage = \Drupal::entityTypeManager()->getStorage('mapping');
  $mappings = $storage->loadByProperties(['type' => 'tractionrec_location']);
  if (!$mappings) {
    return;
  }

  $branch_aliases = [];
  foreach ($mappings as $mapping) {
    $branch_aliases[] = $mapping->get('field_traction_rec_alias')->value;
  }

  $membership_aliases_map = [
    'Family 1' => 'Adult + 1 Youth',
    'Family 2' => 'Adult + Multiple Youth',
    'Family 3' => 'Young Adult + 1 Youth',
    'Family 4' => 'Young Adult + Multiple Youth',
    'Single Adult' => 'Adult',
    'Single Young Adult' => 'Young Adult',
  ];

  foreach ($data as $key => &$membership) {
    $title = $membership['title'];

    foreach ($branch_aliases as $short_branch_alias) {
      if (strpos($title, $short_branch_alias) !== FALSE) {
        // TractionRec membership types have branch prefixes.
        // Ex. TTFY - YOUTH ONLY, TCY - FAMILY 1.
        // The prefixes have to be removed.
        $title = str_replace($short_branch_alias . ' - ', '', $title);
      }
    }

    // 'Add Adult' memberships are not relevant for membership builder.
    if ($title == 'Add Adult') {
      unset($data[$key]);
    }

    // Some of TractionRec membership names are not clear for users.
    // They have to be replaced with more clear custom names by mapping.
    foreach ($membership_aliases_map as $traction_rec_name => $new_membership_name) {
      if (strpos($title, $traction_rec_name) !== FALSE) {
        $title = str_replace($traction_rec_name . ' - ', '', $new_membership_name);
      }
    }

    $membership['title'] = $title;
  }
}
