<?php

/**
 * @file
 * Contains ypkc_salesforce_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ypkc_salesforce_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ypkc_salesforce_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Salesforce migration for YPKC') . '</p>';
      return $output;

    default:
  }
}
