<?php

/**
 * @file
 *
 * Activity Finder altering.
 */

use Drupal\node\NodeInterface;
use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_activity_finder_program_process_results_alter().
 *
 * Adds wait-list capacity data to results.
 */
function openy_tr_activity_finder_activity_finder_program_process_results_alter(array &$data, NodeInterface $entity) {
  $data['price'] = $entity->get('field_price_description')->value;

  $wait_list_availability = !$entity->get('waitlist_capacity')->isEmpty() ? $entity->get('waitlist_capacity')->value : 0;
  $data['wait_list_availability'] = !empty($entity->get('waitlist_unlimited_capacity')->value) ? 1 : $wait_list_availability;
}

/**
 * Implements hook_search_api_query_alter().
 *
 * Hide past sessions in AF.
 */
function ypkc_master_search_api_query_alter(QueryInterface $query) {
  // 'default' index is weird, but such naming is used in the Activity Finder.
  if ($query->getIndex()->id() == 'default') {
    // Show session in AF only if end date is greater than current.
    $query->addCondition('field_session_time_date_end', time(), '>');
  }
}
